apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitor
spec:
  type: LoadBalancer
  selector:
    app: node-exporter
  ports:
    - name: node-exporter
      port: 9100        # Port on which Node Exporter is listening
      targetPort: 9100  # Port on the container where Node Exporter is running