apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: monitor
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: ["pods", "services", "endpoints", "namespaces"]
    verbs: ["get", "list", "watch"]
    # - apiGroups: [""]
    # resources: ["configmaps"]
    # verbs: ["get"]
    # - nonResourceURLs: ["/metrics"]