apiVersion: v1
kind: Service
metadata:
  name: newapp-service
  namespace: monitor  # Specify the namespace here
  annotations:
    prometheus.io/scrape: "true"  # Enable scraping
    prometheus.io/port: "3000"     # The port where metrics are exposed
    prometheus.io/path: "/metrics"  # The path to metrics
spec:
  type: LoadBalancer
  selector:
    app: newapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
